name: Laravel CI (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: fileinfo, xdebug, sqlite3

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Ensure CodeSniffer is Installed
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP CodeSniffer (Linting)
        run: php vendor/bin/phpcs --standard=PSR12 app/

  test:
    runs-on: windows-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: fileinfo, xdebug, sqlite3

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env Example
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Configure SQLite (Tanpa Migrate)
        run: |
          echo "DB_CONNECTION=sqlite" > .env
          echo "DB_DATABASE=/tmp/database.sqlite" >> .env
          touch /tmp/database.sqlite

      - name: Run Tests
        run: php artisan test
